import { useEffect, useRef, useState } from 'react'
import { Dashboard } from './pages/Dashboard'
import { Production } from './pages/Production'
import { FeedPage } from './pages/Feed'
import { SalesPage } from './pages/Sales'
import { HealthPage } from './pages/Health'
import { FlockPage } from './pages/Flocks'
import { FinancePage } from './pages/Finance'
import { ReportPage } from './pages/Reports'

type Nav = 'Dashboard' | 'Produksi' | 'Pakan' | 'Penjualan' | 'Kesehatan' | 'Kandang' | 'Keuangan' | 'Laporan'
type ModalName = 'entry' | 'feed' | 'sale' | 'expense' | 'health' | 'flock' | 'payment' | null
type Flock = { id: string; name: string; strain: string; started: string; hens: number; target: number; active: boolean }
type Entry = { id: string; date: string; flockId: string; total: number; cracked: number; feed: number; deaths: number; note: string }
type Feed = { id: string; date: string; kind: 'Masuk' | 'Keluar'; qty: number; price: number; note: string }
type Sale = { id: string; date: string; customer: string; unit: 'tray' | 'butir' | 'kg'; qty: number; price: number; paid: number; due: string }
type Expense = { id: string; date: string; category: string; amount: number; note: string }
type Health = { id: string; date: string; flockId: string; kind: 'Vaksin' | 'Obat' | 'Gejala' | 'Karantina'; detail: string; qty: number; nextDate: string; note: string }

const today = new Date().toISOString().slice(0, 10)
const navItems: Nav[] = ['Dashboard', 'Produksi', 'Pakan', 'Penjualan', 'Kesehatan', 'Kandang', 'Keuangan', 'Laporan']
const icons: Record<Nav, string> = { Dashboard: '◫', Produksi: '◌', Pakan: '▧', Penjualan: '◈', Kesehatan: '✚', Kandang: '⌂', Keuangan: '◉', Laporan: '▤' }
const seedFlocks: Flock[] = [{ id: 'a', name: 'Kandang A', strain: 'ISA Brown', started: '2026-01-20', hens: 1240, target: 85, active: true }, { id: 'b', name: 'Kandang B', strain: 'Lohmann Brown', started: '2026-01-20', hens: 1186, target: 85, active: true }, { id: 'c', name: 'Kandang C', strain: 'ISA Brown', started: '2026-03-20', hens: 960, target: 85, active: true }]
const seedEntries: Entry[] = [{ id: 'e-a', date: today, flockId: 'a', total: 1128, cracked: 18, feed: 142, deaths: 0, note: '' }, { id: 'e-b', date: today, flockId: 'b', total: 1034, cracked: 15, feed: 138, deaths: 1, note: '' }, { id: 'e-c', date: today, flockId: 'c', total: 756, cracked: 21, feed: 108, deaths: 0, note: 'Pantau produksi.' }]
const seedFeed: Feed[] = [{ id: 'f-1', date: today, kind: 'Masuk', qty: 4000, price: 7200, note: 'PT Nutrifeed' }, { id: 'f-2', date: today, kind: 'Keluar', qty: 388, price: 0, note: 'Pemakaian harian' }]
const seedSales: Sale[] = [{ id: 's-1', date: today, customer: 'UD Maju Jaya', unit: 'tray', qty: 72, price: 40500, paid: 2916000, due: '' }, { id: 's-2', date: today, customer: 'Toko Barokah', unit: 'tray', qty: 32, price: 36000, paid: 0, due: today }]
const seedExpenses: Expense[] = [{ id: 'x-1', date: today, category: 'Tenaga kerja', amount: 350000, note: 'Harian' }, { id: 'x-2', date: today, category: 'Listrik & air', amount: 85000, note: '' }]
const seedHealth: Health[] = [{ id: 'h-1', date: today, flockId: 'c', kind: 'Gejala', detail: 'Produksi menurun', qty: 0, nextDate: '', note: 'Pantau konsumsi pakan dan kotoran.' }]
const key = (name: string) => `farmtelur-${name}-v3`
const money = (n: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n)
function load<T>(name: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(key(name)) ?? 'null') ?? fallback } catch { return fallback } }
function eggQty(s: Sale) { return s.unit === 'tray' ? s.qty * 30 : s.unit === 'butir' ? s.qty : 0 }
function apiFlock(row: { id: string; name: string; strain: string; started_on: string; initial_hens: number; target_hd: string | number; active: boolean }): Flock { return { id: row.id, name: row.name, strain: row.strain, started: row.started_on.slice(0, 10), hens: Number(row.initial_hens), target: Number(row.target_hd), active: row.active } }
function apiEntry(row: { id: string; flock_id: string; recorded_on: string; total_eggs: number; cracked_eggs: number; feed_kg: string | number; deaths: number; note: string }): Entry { return { id: row.id, flockId: row.flock_id, date: row.recorded_on.slice(0, 10), total: Number(row.total_eggs), cracked: Number(row.cracked_eggs), feed: Number(row.feed_kg), deaths: Number(row.deaths), note: row.note } }
function apiFeed(row: { id: string; moved_on: string; kind: Feed['kind']; quantity_kg: string | number; unit_cost: string | number; note: string }): Feed { return { id: row.id, date: row.moved_on.slice(0, 10), kind: row.kind, qty: Number(row.quantity_kg), price: Number(row.unit_cost), note: row.note } }
function apiSale(row: { id: string; sold_on: string; customer: string; unit: Sale['unit']; quantity: string | number; unit_price: string | number; paid: string | number; due_on: string | null }): Sale { return { id: row.id, date: row.sold_on.slice(0, 10), customer: row.customer, unit: row.unit, qty: Number(row.quantity), price: Number(row.unit_price), paid: Number(row.paid), due: row.due_on?.slice(0, 10) ?? '' } }
function apiExpense(row: { id: string; date: string; category: string; amount: string | number; note: string }): Expense { return { id: row.id, date: row.date.slice(0, 10), category: row.category, amount: Number(row.amount), note: row.note } }
function apiHealth(row: { id: string; flock_id: string; date?: string; recorded_on?: string; kind: Health['kind']; detail: string; quantity: string | number; next_on: string | null; note: string }): Health { return { id: row.id, flockId: row.flock_id, date: (row.date ?? row.recorded_on ?? '').slice(0, 10), kind: row.kind, detail: row.detail, qty: Number(row.quantity), nextDate: row.next_on?.slice(0, 10) ?? '', note: row.note } }
async function request<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? 'Gagal menghubungi server.'); return body }
function App() {
  const [authenticated, setAuthenticated] = useState<boolean | null>(null); const [page, setPage] = useState<Nav>('Dashboard'); const [date, setDate] = useState(today); const [rangeStart, setRangeStart] = useState(today); const [rangeEnd, setRangeEnd] = useState(today); const [modal, setModal] = useState<ModalName>(null); const [notice, setNotice] = useState(''); const [confirm, setConfirm] = useState<null | { text: string; action: () => void }>(null); const [payment, setPayment] = useState<Sale | null>(null)
  const [flocks, setFlocks] = useState<Flock[]>(() => load('flocks', seedFlocks)); const [entries, setEntries] = useState<Entry[]>(() => load('entries', seedEntries)); const [feed, setFeed] = useState<Feed[]>(() => load('feed', seedFeed)); const [sales, setSales] = useState<Sale[]>(() => load('sales', seedSales)); const [expenses, setExpenses] = useState<Expense[]>(() => load('expenses', seedExpenses)); const [health, setHealth] = useState<Health[]>(() => load('health', seedHealth))
  useEffect(() => { request('/api/auth/me').then(() => setAuthenticated(true)).catch(() => setAuthenticated(false)) }, [])
  useEffect(() => { if (!authenticated) return; request<Parameters<typeof apiFlock>[0][]>('/api/flocks').then(rows => setFlocks(rows.map(apiFlock))).catch(error => setNotice(error instanceof Error ? error.message : 'Gagal memuat kandang.')) }, [authenticated])
  useEffect(() => { if (!authenticated) return; request<Parameters<typeof apiEntry>[0][]>(`/api/production?date=${date}`).then(rows => setEntries(rows.map(apiEntry))).catch(() => undefined); request<Parameters<typeof apiFeed>[0][]>(`/api/feed?date=${date}`).then(rows => setFeed(rows.map(apiFeed))).catch(() => undefined); request<Parameters<typeof apiSale>[0][]>(`/api/sales?date=${date}`).then(rows => setSales(rows.map(apiSale))).catch(() => undefined); request<Parameters<typeof apiExpense>[0][]>(`/api/expenses?date=${date}`).then(rows => setExpenses(rows.map(apiExpense))).catch(() => undefined); request<Parameters<typeof apiHealth>[0][]>(`/api/health-records?date=${date}`).then(rows => Array.isArray(rows) && setHealth(rows.map(apiHealth))).catch(() => undefined) }, [date, authenticated])
  if (authenticated === null) return <main className="login-shell">Memuat sesi…</main>
  if (!authenticated) return <Login onSuccess={() => setAuthenticated(true)} />
  const activeFlocks = flocks.filter(f => f.active); const feedStock = feed.reduce((n, f) => n + (f.kind === 'Masuk' ? f.qty : -f.qty), 0); const eggStock = entries.reduce((n, e) => n + e.total - e.cracked, 0) - sales.reduce((n, s) => n + eggQty(s), 0); const revenue = sales.filter(s => s.date === date).reduce((n, s) => n + s.qty * s.price, 0); const receivable = sales.reduce((n, s) => n + s.qty * s.price - s.paid, 0); const eggs = entries.filter(e => e.date === date).reduce((n, e) => n + e.total - e.cracked, 0)
  const go = (p: Nav) => { setPage(p); setModal(null); setConfirm(null) }
  async function addEntry(v: Omit<Entry, 'id'>) { try { const row = await request<Parameters<typeof apiEntry>[0]>(`/api/production/${v.flockId}/${v.date}`, { method: 'PUT', body: JSON.stringify(v) }); const item = apiEntry(row); setEntries(prev => [item, ...prev.filter(e => e.id !== item.id && !(e.date === item.date && e.flockId === item.flockId))]); setModal(null); setNotice('Catatan produksi tersimpan ke server.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Gagal menyimpan produksi.') } }
  async function addFeed(v: Omit<Feed, 'id'>) { try { const row = await request<Parameters<typeof apiFeed>[0]>('/api/feed', { method: 'POST', body: JSON.stringify({ movedOn: v.date, kind: v.kind, quantity: v.qty, unitCost: v.price, note: v.note }) }); setFeed(prev => [apiFeed(row), ...prev]); setModal(null); setNotice('Mutasi pakan tersimpan ke server.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Gagal menyimpan pakan.') } }
  async function addSale(v: Omit<Sale, 'id'>) { try { const row = await request<Parameters<typeof apiSale>[0]>('/api/sales', { method: 'POST', body: JSON.stringify({ soldOn: v.date, customer: v.customer, unit: v.unit, quantity: v.qty, unitPrice: v.price, dueOn: v.due || null, paid: v.paid }) }); setSales(prev => [apiSale(row), ...prev]); setModal(null); setNotice('Penjualan tersimpan ke server.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Gagal menyimpan penjualan.') } }
  async function addFlock(v: Omit<Flock, 'id'>) { try { const row = await request<Parameters<typeof apiFlock>[0]>('/api/flocks', { method: 'POST', body: JSON.stringify({ name: v.name, strain: v.strain, startedOn: v.started, initialHens: v.hens, targetHd: v.target }) }); setFlocks(prev => [apiFlock(row), ...prev]); setModal(null); setNotice('Kandang/batch tersimpan ke server.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Gagal menyimpan kandang.') } }
  async function addHealth(v: Omit<Health, 'id'>) { try { const row = await request<Parameters<typeof apiHealth>[0]>('/api/health-records', { method: 'POST', body: JSON.stringify({ flock_id: v.flockId, recorded_on: v.date, kind: v.kind, detail: v.detail, quantity: v.qty, next_on: v.nextDate || null, note: v.note }) }); setHealth(prev => [apiHealth({ ...row, date: row.recorded_on } as Parameters<typeof apiHealth>[0]), ...prev]); setModal(null); setNotice('Catatan kesehatan tersimpan ke server.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Gagal menyimpan kesehatan.') } }
  async function addExpense(v: Omit<Expense, 'id'>) { try { const row = await request<{ id: string; spent_on: string; category: string; amount: string | number; note: string }>('/api/expenses', { method: 'POST', body: JSON.stringify({ spent_on: v.date, category: v.category, amount: v.amount, note: v.note }) }); setExpenses(prev => [{ id: row.id, date: row.spent_on.slice(0, 10), category: row.category, amount: Number(row.amount), note: row.note }, ...prev]); setModal(null); setNotice('Biaya tersimpan ke server.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Gagal menyimpan biaya.') } }
  async function receivePayment(amount: number) { if (!payment) return; try { await request(`/api/sales/${payment.id}/payments`, { method: 'POST', body: JSON.stringify({ paidOn: date, amount }) }); setSales(prev => prev.map(s => s.id === payment.id ? { ...s, paid: s.paid + amount } : s)); setPayment(null); setModal(null); setNotice('Pembayaran tersimpan ke server.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Gagal menyimpan pembayaran.') } }
  async function destroy(kind: 'health' | 'expense' | 'flock', id: string) { try { if (kind === 'flock') { await request(`/api/flocks/${id}/archive`, { method: 'PATCH' }); setFlocks(prev => prev.map(x => x.id === id ? { ...x, active: false } : x)); setNotice('Batch diarsipkan di server.') } if (kind === 'health') { await request(`/api/health-records/${id}`, { method: 'DELETE' }); setHealth(prev => prev.filter(x => x.id !== id)); setNotice('Data dihapus dari server.') } if (kind === 'expense') { await request(`/api/expenses/${id}`, { method: 'DELETE' }); setExpenses(prev => prev.filter(x => x.id !== id)); setNotice('Data dihapus dari server.') } setConfirm(null) } catch (error) { setNotice(error instanceof Error ? error.message : 'Gagal mengarsipkan batch.') } }
  const cta = page === 'Produksi' ? ['entry', 'Catat produksi'] : page === 'Pakan' ? ['feed', 'Mutasi pakan'] : page === 'Penjualan' ? ['sale', 'Catat penjualan'] : page === 'Kesehatan' ? ['health', 'Catat kesehatan'] : page === 'Kandang' ? ['flock', 'Tambah batch'] : page === 'Keuangan' || page === 'Laporan' ? ['expense', 'Catat biaya'] : null
  return <div className="app-shell"><aside className="sidebar"><Brand /><Nav active={page} go={go} /><User /></aside><main className="main-content"><header className="page-header"><div><p className="eyebrow">OPERASIONAL PETERNAKAN</p><h1>{page === 'Dashboard' ? 'Selamat pagi, Fai.' : page}</h1><p className="muted">{description(page)}</p></div><div className="header-actions"><label className="date-filter">Tanggal<input type="date" value={date} onChange={e => setDate(e.target.value)} /></label>{cta && <button className="primary-button" onClick={() => setModal(cta[0] as ModalName)}>＋ {cta[1]}</button>}</div></header>{notice && <div className="notice" role="status">✓ {notice}<button onClick={() => setNotice('')} aria-label="Tutup">×</button></div>}
  {page === 'Dashboard' && <Dashboard eggs={eggs} eggStock={eggStock} feedStock={feedStock} revenue={revenue} onGo={go} />}
  {page === 'Produksi' && <Production items={entries.filter(x => x.date === date)} flocks={flocks} />}
  {page === 'Pakan' && <FeedPage items={feed.filter(x => x.date === date)} stock={feedStock} />}
  {page === 'Penjualan' && <SalesPage items={sales.filter(x => x.date === date)} stock={eggStock} receivable={receivable} onPay={s => { setPayment(s); setModal('payment') }} />}
  {page === 'Kesehatan' && <HealthPage items={health.filter(x => x.date === date)} flocks={flocks} onDelete={id => setConfirm({ text: 'Hapus catatan kesehatan ini?', action: () => destroy('health', id) })} />}
  {page === 'Kandang' && <FlockPage flocks={flocks} entries={entries.filter(e => e.date === date)} onArchive={id => setConfirm({ text: 'Arsipkan batch ini? Data riwayat tetap tersimpan.', action: () => destroy('flock', id) })} />}
  {page === 'Keuangan' && <FinancePage date={date} sales={sales} feed={feed} expenses={expenses} onAdd={() => setModal('expense')} onDelete={id => setConfirm({ text: 'Hapus biaya ini?', action: () => destroy('expense', id) })} />}
  {page === 'Laporan' && <ReportPage start={rangeStart} end={rangeEnd} setStart={setRangeStart} setEnd={setRangeEnd} entries={entries} sales={sales} feed={feed} expenses={expenses} />}
  </main><nav className="mobile-nav"><Nav active={page} go={go} /></nav>
  {modal === 'entry' && <EntryForm date={date} flocks={activeFlocks} onClose={() => setModal(null)} onSave={addEntry} />}{modal === 'feed' && <FeedForm date={date} stock={feedStock} onClose={() => setModal(null)} onSave={addFeed} />}{modal === 'sale' && <SaleForm date={date} stock={eggStock} onClose={() => setModal(null)} onSave={addSale} />}{modal === 'expense' && <ExpenseForm date={date} onClose={() => setModal(null)} onSave={addExpense} />}{modal === 'health' && <HealthForm date={date} flocks={activeFlocks} onClose={() => setModal(null)} onSave={addHealth} />}{modal === 'flock' && <FlockForm onClose={() => setModal(null)} onSave={addFlock} />}{modal === 'payment' && payment && <PaymentForm sale={payment} onClose={() => setModal(null)} onSave={receivePayment} />}{confirm && <Confirm text={confirm.text} onCancel={() => setConfirm(null)} onConfirm={confirm.action} />}</div>
}
function Login({ onSuccess }: { onSuccess: () => void }) { const [error, setError] = useState(''); return <main className="login-shell"><form className="login-card" onSubmit={async e => { e.preventDefault(); try { await request('/api/auth/login', { method: 'POST', body: JSON.stringify({ password: new FormData(e.currentTarget).get('password') }) }); onSuccess() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Login gagal.') } }}><div className="brand"><span className="brand-mark">◉</span><span>Farm<span>Telur</span></span></div><h1>Login Owner</h1><p>Masuk untuk mengelola operasional peternakan.</p><label>Password<input name="password" type="password" autoComplete="current-password" required autoFocus /></label>{error && <p className="login-error" role="alert">{error}</p>}<button className="primary-button">Masuk</button></form></main> }
function description(p: Nav) { return ({ Dashboard: 'Ringkasan usaha berdasarkan tanggal terpilih.', Produksi: 'Satu catatan per kandang per hari.', Pakan: 'Kontrol stok dan mutasi pakan.', Penjualan: 'Kelola invoice, stok telur, dan piutang.', Kesehatan: 'Riwayat vaksin, obat, gejala, dan karantina.', Kandang: 'Master kandang dan batch ayam aktif.', Keuangan: 'Pendapatan, biaya, dan laba rugi operasional.', Laporan: 'Ekspor ringkasan operasional.' } as Record<Nav, string>)[p] }
function Brand() { return <><div className="brand"><span className="brand-mark">◉</span><span>Farm<span>Telur</span></span></div><p className="farm-label">CV Sumber Protein</p></> } function User() { return <div className="sidebar-bottom"><div className="user-dot">FR</div><div><b>Fai Rifai</b><small>Owner</small></div></div> } function Nav({ active, go }: { active: Nav; go: (p: Nav) => void }) { return <div className="nav-buttons">{navItems.map(x => <button key={x} className={`nav-item ${x === active ? 'active' : ''}`} onClick={() => go(x)}><span>{icons[x]}</span><em>{x}</em></button>)}</div> }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { const ref = useRef<HTMLButtonElement>(null); useEffect(() => { ref.current?.focus(); const k = (e: KeyboardEvent) => e.key === 'Escape' && onClose(); addEventListener('keydown', k); return () => removeEventListener('keydown', k) }, [onClose]); return <div className="modal-layer"><button className="modal-backdrop" onClick={onClose} aria-label="Tutup" /><section className="entry-modal" role="dialog" aria-modal="true"><div className="modal-head"><h2>{title}</h2><button ref={ref} onClick={onClose} aria-label="Tutup">×</button></div>{children}</section></div> }
function EntryForm({ date, flocks, onClose, onSave }: { date: string; flocks: Flock[]; onClose: () => void; onSave: (x: Omit<Entry, 'id'>) => void }) { return <Modal title="Catat produksi" onClose={onClose}><form onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); const total = Number(d.get('total')), cracked = Number(d.get('cracked')); if (cracked > total) return; onSave({ date: String(d.get('date')), flockId: String(d.get('flock')), total, cracked, feed: Number(d.get('feed')), deaths: Number(d.get('deaths')), note: String(d.get('note')) }) }}><DateField date={date}/><label>Kandang<select name="flock">{flocks.map(f => <option value={f.id} key={f.id}>{f.name}</option>)}</select></label><div className="form-row"><label>Telur total<input name="total" min="0" required type="number" /></label><label>Telur retak<input name="cracked" min="0" defaultValue="0" required type="number" /></label></div><div className="form-row"><label>Pakan kg<input name="feed" min="0" defaultValue="0" required type="number" /></label><label>Mati<input name="deaths" min="0" defaultValue="0" required type="number" /></label></div><label>Catatan<input name="note" /></label><button className="primary-button">Simpan</button></form></Modal> }
function FeedForm({ date, stock, onClose, onSave }: { date: string; stock: number; onClose: () => void; onSave: (x: Omit<Feed, 'id'>) => void }) { return <Modal title="Mutasi pakan" onClose={onClose}><form onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); const qty = Number(d.get('qty')); const kind = String(d.get('kind')) as Feed['kind']; if (kind === 'Keluar' && qty > stock) return; onSave({ date: String(d.get('date')), kind, qty, price: Number(d.get('price')), note: String(d.get('note')) }) }}><DateField date={date}/><label>Jenis<select name="kind"><option>Masuk</option><option>Keluar</option></select></label><div className="form-row"><label>Jumlah kg<input name="qty" min="0.1" required step="0.1" type="number" /></label><label>Harga/kg<input name="price" min="0" defaultValue="0" required type="number" /></label></div><label>Catatan<input name="note" /></label><button className="primary-button">Simpan</button></form></Modal> }
function SaleForm({ date, stock, onClose, onSave }: { date: string; stock: number; onClose: () => void; onSave: (x: Omit<Sale, 'id'>) => void }) { return <Modal title="Catat penjualan" onClose={onClose}><form onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); const unit = String(d.get('unit')) as Sale['unit']; const qty = Number(d.get('qty')); if ((unit === 'tray' ? qty * 30 : unit === 'butir' ? qty : 0) > stock) return; onSave({ date: String(d.get('date')), customer: String(d.get('customer')), unit, qty, price: Number(d.get('price')), paid: Number(d.get('paid')), due: String(d.get('due')) }) }}><DateField date={date}/><label>Pelanggan<input name="customer" required /></label><label>Satuan<select name="unit"><option>tray</option><option>butir</option><option>kg</option></select></label><div className="form-row"><label>Qty<input name="qty" min="1" required type="number" /></label><label>Harga<input name="price" min="0" required type="number" /></label></div><div className="form-row"><label>Dibayar<input name="paid" min="0" defaultValue="0" required type="number" /></label><label>Jatuh tempo<input name="due" type="date" /></label></div><button className="primary-button">Simpan</button></form></Modal> }
function ExpenseForm({ date, onClose, onSave }: { date: string; onClose: () => void; onSave: (x: Omit<Expense, 'id'>) => void }) { return <Modal title="Catat biaya" onClose={onClose}><form onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); onSave({ date: String(d.get('date')), category: String(d.get('category')), amount: Number(d.get('amount')), note: String(d.get('note')) }) }}><DateField date={date}/><label>Kategori<select name="category"><option>Tenaga kerja</option><option>Listrik & air</option><option>Obat & vaksin</option><option>Transport</option><option>Perbaikan kandang</option><option>Lainnya</option></select></label><label>Nilai biaya<input name="amount" min="1" required type="number" /></label><label>Catatan<input name="note" /></label><button className="primary-button">Simpan</button></form></Modal> }
function HealthForm({ date, flocks, onClose, onSave }: { date: string; flocks: Flock[]; onClose: () => void; onSave: (x: Omit<Health, 'id'>) => void }) { return <Modal title="Catat kesehatan" onClose={onClose}><form onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); onSave({ date: String(d.get('date')), flockId: String(d.get('flock')), kind: String(d.get('kind')) as Health['kind'], detail: String(d.get('detail')), qty: Number(d.get('qty')), nextDate: String(d.get('nextDate')), note: String(d.get('note')) }) }}><DateField date={date}/><label>Kandang<select name="flock">{flocks.map(f => <option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>Jenis<select name="kind"><option>Vaksin</option><option>Obat</option><option>Gejala</option><option>Karantina</option></select></label><div className="form-row"><label>Detail<input name="detail" required placeholder="Contoh: ND LaSota" /></label><label>Jumlah<input name="qty" min="0" defaultValue="0" type="number" /></label></div><label>Jadwal berikutnya<input name="nextDate" type="date" /></label><label>Catatan<input name="note" /></label><button className="primary-button">Simpan</button></form></Modal> }
function FlockForm({ onClose, onSave }: { onClose: () => void; onSave: (x: Omit<Flock, 'id'>) => void }) { return <Modal title="Tambah kandang/batch" onClose={onClose}><form onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); onSave({ name: String(d.get('name')), strain: String(d.get('strain')), started: String(d.get('started')), hens: Number(d.get('hens')), target: Number(d.get('target')), active: true }) }}><label>Nama kandang<input name="name" required placeholder="Kandang D" /></label><label>Strain<select name="strain"><option>ISA Brown</option><option>Lohmann Brown</option><option>Hy-Line Brown</option><option>Lainnya</option></select></label><div className="form-row"><label>Mulai produksi<input name="started" required type="date" defaultValue={today} /></label><label>Populasi awal<input name="hens" min="1" required type="number" /></label></div><label>Target HD (%)<input name="target" min="1" max="100" defaultValue="85" required type="number" /></label><button className="primary-button">Simpan batch</button></form></Modal> }
function PaymentForm({ sale, onClose, onSave }: { sale: Sale; onClose: () => void; onSave: (v: number) => void }) { const debt = sale.qty * sale.price - sale.paid; return <Modal title="Terima pembayaran" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSave(Number(new FormData(e.currentTarget).get('amount'))) }}><p className="payment-detail">{sale.customer}<b>Sisa piutang: {money(debt)}</b></p><label>Nominal<input name="amount" min="1" max={debt} required type="number" /></label><button className="primary-button">Simpan pembayaran</button></form></Modal> }
function DateField({ date }: { date: string }) { return <label>Tanggal<input name="date" required type="date" defaultValue={date} /></label> } function Confirm({ text, onCancel, onConfirm }: { text: string; onCancel: () => void; onConfirm: () => void }) { return <Modal title="Konfirmasi" onClose={onCancel}><p className="confirm-text">{text}</p><div className="confirm-actions"><button className="select-button" onClick={onCancel}>Batal</button><button className="danger-button confirm-delete" onClick={onConfirm}>Ya, lanjutkan</button></div></Modal> }
export default App
// maintenance: localStorage adapters are deliberate until backend arrives; replace only load/save calls with API adapters.
